name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Vet (análise estática)
        run: go vet ./...

      - name: Testes
        run: go test -v ./...

      - name: Build
        run: go build -v ./...
